"""Numerics, independent storage, real gradient strides, and composed checkpoint checks."""
from typing import Callable, cast

import pytest

pytest.importorskip("triton")
import torch
from torch import Tensor

from model.layers.attention import precompute_freqs_cis, qkv_bias_rope as reference
from .rope import packed_backward, qkv_bias_rope, supports


@pytest.mark.gpu
@pytest.mark.slow
@pytest.mark.parametrize("compiled", [False, True])
@pytest.mark.parametrize("gathered", [False, True])
@pytest.mark.parametrize("bias_enabled", [False, True])
def test_packed_parity(compiled: bool, gathered: bool, bias_enabled: bool) -> None:
    torch.manual_seed(42)
    qkv = torch.randn(2, 17, 384, device="cuda", dtype=torch.bfloat16).requires_grad_()
    bias = torch.randn(2, 1, 4, 32, device="cuda", requires_grad=True) if bias_enabled else None
    table = precompute_freqs_cis(32, 17, 50000).cuda()
    if gathered:
        positions = torch.arange(34, device="cuda").reshape(2, 17) % 7
        table = table[0, positions]
    assert supports(bias, qkv, table, 4)
    expected = reference(bias, qkv, table, 4)
    fn = torch.compile(qkv_bias_rope, fullgraph=True, dynamic=True) if compiled else qkv_bias_rope
    actual = fn(bias, qkv, table, 4)
    for value, ref in zip(actual, expected, strict=True):
        torch.testing.assert_close(value, ref, atol=0, rtol=0)
        assert value.untyped_storage().data_ptr() != qkv.untyped_storage().data_ptr()
        assert value.untyped_storage().nbytes() == value.numel() * value.element_size()
    # Heads-first gradients exercise the layout generated by FlexAttention.
    grads = [torch.randn(2, 4, 17, 32, device="cuda", dtype=qkv.dtype).transpose(1, 2) for _ in range(3)]
    params = (qkv, bias) if bias is not None else (qkv,)
    expected_grads = torch.autograd.grad(expected, params, grads)
    actual_grads = torch.autograd.grad(actual, params, grads)
    for value, ref in zip(actual_grads, expected_grads, strict=True):
        torch.testing.assert_close(value, ref, atol=1e-4, rtol=1e-5)
    repeated = fn(bias, qkv, table, 4)
    repeated_grads = torch.autograd.grad(repeated, params, grads)
    for value, repeated_value in zip(actual_grads, repeated_grads, strict=True):
        torch.testing.assert_close(value, repeated_value, atol=0, rtol=0)
    # Unused outputs supply zero tangents; the V-only route must be identity.
    v = fn(bias, qkv, table, 4)[2]
    v_grad = torch.autograd.grad(v.sum(), qkv)[0]
    torch.testing.assert_close(v_grad[..., :256], torch.zeros_like(v_grad[..., :256]), atol=0, rtol=0)
    torch.testing.assert_close(v_grad[..., 256:], torch.ones_like(v_grad[..., 256:]), atol=0, rtol=0)


def test_cpu_inputs_raise_with_disable_guidance() -> None:
    qkv = torch.randn(1, 9, 36, requires_grad=True)
    table = precompute_freqs_cis(6, 9, 50000).requires_grad_()
    assert not supports(None, qkv, table, 2)
    with pytest.raises(RuntimeError, match='use_custom_kernels: false'):
        qkv_bias_rope(None, qkv, table, 2)


@pytest.mark.gpu
@pytest.mark.slow
@pytest.mark.parametrize("dtype", [torch.float32, torch.float16])
def test_other_dtypes(dtype: torch.dtype) -> None:
    qkv = torch.randn(1, 13, 192, device="cuda", dtype=dtype, requires_grad=True)
    table = precompute_freqs_cis(32, 13, 50000).cuda()
    bias = torch.randn(2, 1, 2, 32, device="cuda", requires_grad=True)
    actual = qkv_bias_rope(bias, qkv, table, 2)
    expected = reference(bias, qkv, table, 2)
    for value, ref in zip(actual, expected, strict=True):
        torch.testing.assert_close(value, ref, atol=0, rtol=0)
    gradients = [torch.randn_like(x) for x in actual]
    for value, ref in zip(torch.autograd.grad(actual, (qkv, bias), gradients),
                          torch.autograd.grad(expected, (qkv, bias), gradients), strict=True):
        torch.testing.assert_close(value, ref, atol=1e-4, rtol=1e-5)


@pytest.mark.gpu
@pytest.mark.slow
@pytest.mark.parametrize("dtype", [torch.bfloat16, torch.float16])
def test_promoted_tangents_and_compiled_loss(dtype: torch.dtype) -> None:
    torch.manual_seed(63)
    table = precompute_freqs_cis(32, 17, 50000).cuda()
    base = torch.randn(2, 17, 384, device="cuda", requires_grad=True)
    tangents = [torch.randn(2, 17, 4, 32, device="cuda") for _ in range(3)]
    # Direct compiled backward isolates the promotion boundary even when AOT
    # chooses to retain tangent casts in the end-to-end loss below.
    expected = torch.autograd.grad(reference(None, base, table, 4), base, tangents)[0].to(dtype)
    backward = cast(Callable[..., tuple[Tensor, Tensor]], torch.compile(packed_backward, fullgraph=True))
    packed, partial = backward(tangents[0], tangents[1], tangents[2], table, True, dtype)
    assert packed.dtype == dtype
    torch.testing.assert_close(packed, expected, atol=0, rtol=0)
    rounded_q, rounded_k, _ = expected.reshape(2, 17, 3, 4, 32).unbind(2)
    dbias = torch.stack([rounded_q.float().sum((0, 1)), rounded_k.float().sum((0, 1))])
    torch.testing.assert_close(partial.sum(0), dbias, atol=1e-4, rtol=1e-5)

    def loss(qkv: Tensor, bias: Tensor) -> Tensor:
        q, k, v = qkv_bias_rope(bias, qkv, table, 4)
        return torch.stack([(x.float().square() * tangent).sum() for x, tangent in zip((q, k, v), tangents)]).sum()

    qkv = base.detach().to(dtype).requires_grad_()
    bias = torch.randn(2, 1, 4, 32, device="cuda", requires_grad=True)
    expected_outputs = reference(bias, qkv, table, 4)
    expected_loss = torch.stack([(x.float().square() * t).sum() for x, t in zip(expected_outputs, tangents)]).sum()
    expected_grads = torch.autograd.grad(expected_loss, (qkv, bias))
    actual_loss = torch.compile(loss, fullgraph=True)(qkv, bias)
    actual_grads = torch.autograd.grad(actual_loss, (qkv, bias))
    for value, ref in zip(actual_grads, expected_grads, strict=True):
        torch.testing.assert_close(value, ref, atol=1e-4, rtol=1e-5)




@pytest.mark.gpu
def test_unsupported_cuda_layout_and_table_grad_raise() -> None:
    qkv = torch.randn(1, 18, 192, device="cuda", requires_grad=True)[:, ::2]
    table = precompute_freqs_cis(32, 9, 50000).cuda()
    for value, freqs in [(qkv, table), (qkv.contiguous(), table.requires_grad_())]:
        assert not supports(None, value, freqs, 2)
        with pytest.raises(RuntimeError, match='use_custom_kernels: false'):
            qkv_bias_rope(None, value, freqs, 2)
